spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://10.198.254.1:8848
security:
  oauth2:
    client:
      client-id: client_1
      client-secret: admin
    #      user-authorization-uri: http://127.0.0.1:8080/auth/oauth/authorize    #直接配置认证中心端口(http://127.0.0.1:11000/oauth/authorize)，也可以配置网关端口
    #      access-token-uri: http://127.0.0.1:8080/auth/token              #直接配置认证中心端口(http://127.0.0.1:11000/oauth/authorize)，也可以配置网关端口
    resource:
      token-info-uri: 'http://127.0.0.1:11000/token/oauth/check_token' #直接配置认证中心端口(http://127.0.0.1:11000/oauth/authorize)，也可以配置网关端口

logging:
  level:
    com.ws.icloud: debug

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000
